# Generated by Django 5.0.6 on 2025-03-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('production_year', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
